OnlineRestaurantMenu/Models/Food.cs
namespace OnlineRestaurantMenu.Models
{
    public class Food
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Calories { get; set; }
        public string Description { get; set; }
        public int TimeToGet { get; set; }
        public string Image { get; set; }
        public int  Size { get; set; }

    }
}

OnlineRestaurantMenu/Models/Menu/MenuFoodModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using static OnlineRestaurantMenu.Infrastructure.Data.Constants.DataConstants.FoodType;

namespace OnlineRestaurantMenu.Models.Menu
{
    public class MenuFoodModel
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [StringLength(FOOD_TYPE_NAME_MAX_LENGTH, MinimumLength = FOOD_TYPE_NAME_MIN_LENGTH)]
        public string Type { get; set; } = null!;
        [Required]
        [StringLength(FOOD_TYPE_IMAGE_MAX_LENGTH, MinimumLength = FOOD_TYPE_IMAGE_MIN_LENGTH)]
        public string Image { get; set; } = null!;

    }
}

OnlineRestaurantMenu/Controllers/MenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineRestaurantMenu.Contracts;

namespace Watchlist.Controllers
{
    [Authorize]
    public class MenuController : Controller
    {
        private readonly IMenuServise menuServise;
        public MenuController(IMenuServise _menuServise)
        {
            menuServise=_menuServise;
        }
        [HttpGet]
        public async Task<IActionResult> FoodsTypes()
        {
            var model = await menuServise.GetAllFoodTypesAsync();
            return View(model);
        }
        public async Task<IActionResult> DrinksTypes()
        {
            var model = await menuServise.GetAllDrinkTypesAsync();
            return View(model);
        }
        public async Task<IActionResult> FoodsByType(int id)
        {
            var model = await menuServise.GetAllFoodByType(id);
            return View(model);
        }
        public async Task<IActionResult> DrinksByType(int id)
        {
            var model = await menuServise.GetAllDrinkByType(id);
            return View(model);
        }


    }
}

OnlineRestaurantMenu/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineRestaurantMenu.Contracts;
using OnlineRestaurantMenu.DropBox;
using OnlineRestaurantMenu.Infrastructure.Data.Entity;
using OnlineRestaurantMenu.Models;
using OnlineRestaurantMenu.Models.Product;
using OnlineRestaurantMenu.Models.Role;
using OnlineRestaurantMenu.Service;
using System.Security.Claims;

namespace OnlineRestaurantMenu.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductServise productService;
        public ProductController(IProductServise _productServise)
        {
            productService = _productServise;
        }

        [HttpGet]
        public async Task<IActionResult> AddDrink()
        {
            AddProductModel model = new AddProductModel()
            {
                ProductTypes = (List<ProductTypesModel>)await productService.GetDrinkTypesAsync(),
            };
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> AddFood()
        {
            var model = new AddProductModel()
            {
                ProductTypes = (List<ProductTypesModel>)await productService.GetFoodTypesAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddDrink(AddProductModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await productService.AddProductAsync(model);
                return RedirectToAction(nameof(AllDrinks));
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Something went wrong");
                return View(model);
            }
        }
        [HttpPost]
        public async Task<IActionResult> AddFood(AddProductModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await productService.AddFoodAsync(model);
                return RedirectToAction(nameof(AllFoods));
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Something went wrong");
                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> AllDrinks(int pg = 1)
        {
            var model = await productService.GetAllDrinksAsync();

            const int pageSize = 5;
            if (pg < 1)
            {
                pg = 1;
            }
            int resCount = model.Count();
            var pager = new Pager(resCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = model.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;

            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> AllFoods(int pg = 1)
        {
            var model = await productService.GetAllFoodsAsync();

            const int pageSize = 5;
            if (pg < 1)
            {
                pg = 1;
            }
            int resCount = model.Count();
            var pager = new Pager(resCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = model.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;

            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> EditDrink(int Id)
        {
            var model = await productService.EditDrink(Id);
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> EditFood(int Id)
        {
            var model = await productService.EditFood(Id);
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> RemoveProduct(int Id)
        {
            await productService.RemoveProductAsync(Id);
            if (Id == 1)
            {
                return RedirectToAction(nameof(AllDrinks));
            }
            else
            {
                return RedirectToAction(nameof(AllFoods));
            }
            
            
        }
        [HttpPost]
        public async Task<IActionResult> EditDrink(ProductModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await productService.EditProduct(model);
                return RedirectToAction(nameof(AllDrinks));
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Something went wrong");
                return View(model);
            }

        }
        [HttpPost]
        public async Task<IActionResult> EditFood(ProductModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await productService.EditProduct(model);
                return RedirectToAction(nameof(AllFoods));
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Something went wrong");
                return View(model);
            }

        }

      
         [HttpPost]
        public async Task<IActionResult> AddInOrder(OrderModel model)
        {
            var userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;

            await productService.AddProdyctInOrderAsync(model, userId);

          
            var model1 = await productService.GetMyItems(userId);
            return View(model1);
        }
        [HttpGet]
        public async Task<IActionResult> AddInOrder()
        {
           
            var userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;
            var model = await productService.GetMyItems(userId);
            var tables = await productService.GetTablesAsync();
            ViewData["Tables"] = tables;
          
            return View(model);

            
        }
       
        public async Task<IActionResult> RemoveProductFromOrder(int id)
        {
            var userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;
            await productService.RemoveProductAsync(id);

            var model1 = await productService.GetMyItems(userId);
            return View(nameof(AddInOrder));
        }
       /* public async Task<IActionResult> SearchProduct(string? searchTerm = null, int pages = 1,int productPerPage=3)
        {
            var products= new List<Product>();
            if (string.IsNullOrEmpty(searchTerm) == false)
            {
                searchTerm = $"%{searchTerm.ToLower()}%";
                products = products
                    .Where(c => EF.Functions.Like(c.Make, searchTerm)
                    EF.Functions.Like(c.CarModel, searchTerm)
                    EF.Functions.Like(c.Description.ToLower(), searchTerm));
            }
            return View(nameof(AddInOrder));
        }*/
        







    }
}


    
    
    
    

OnlineRestaurantMenu/Views/Menu/DrinksByType.cshtml
@using OnlineRestaurantMenu.Models.Product;
@model IEnumerable<ProductModel>


@{
   
}

<div class="container pb-5" style="background-color:rgb(220,220,220,0.1)">

        <div class="p-5  bg-image" style="
        background-image: url('https://i.postimg.cc/9XLYf0xf/pexels-ella-olsson-1640777.jpg');
        background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
border-end-end-radius: 80px;
border-end-start-radius:80px;
  position: relative;
        height: 380px;"></div>

    <div class="text-center mb-2">
        <h1 class="text-black">Меню</h1>

        <div class="d-flex justify-content-center">
            <a class="nav-link btn btn-primary" style="color:white; margin-right:10px" asp-controller="Menu" asp-action="FoodsTypes">Храни</a>
            <a class="nav-link btn btn-primary" style="color:white" asp-controller="Menu" asp-action="DrinksTypes">Напитки</a>
        </div>

    </div>
    <div class="input-group px-5">
        <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
        <button asp-action="SearchProduct" asp-controller="Product" type="button" class="btn btn-primary">search</button>
    </div>
    <div class="row px-5 mt-3">
        @foreach (var food in Model)
        {
            <form asp-action="AddInOrder" asp-controller="Product" method="post" enctype="multipart/form-data">
            <div class="col-sm-6 col-md-6 col-lg-4">
                <div class="food-card">
                    <div class="food-card_img">
                            <input type="hidden" asp-for="@Model.Where(x=>x.Id==food.Id).FirstOrDefault()!.Name" />
                        <img src="@food.Image" alt="">
                    </div>
                    <div class="food-card_content">
                        <div class="food-card_title-section">
                            <a href="#!" class="food-card_title">@food.Name</a>
                            <div class="row">
                                <div class="col text-center">

                                    <img src="~/svg/weight-svgrepo-com.svg" alt="" width="25px" height="25px" style="vertical-align: text-bottom;" />@food.Size


                                </div>
                                <div class="col text-center">
                                    <img src="~/svg/stopwatch.svg" alt="" width="25px" height="25px" style="vertical-align: text-bottom;" />@food.TimeToGet мин.
                                </div>
                                <div class="col text-center">
                                    <img src="~/svg/egg-fried.svg" alt="" width="25px" height="25px" style="vertical-align: text-bottom;" />@food.Calories Kcal
                                </div>

                            </div>
                            <p>@food.Description</p>
                        </div>
                        <div class="food-card_bottom-section">
                            @*<div class="space-between">
                        <div>
                        <span class="fa fa-fire"></span> 220 - 280 Kcal
                        </div>
                        </div>*@
                            <hr>
                            <div class="space-between">
                                <div class="food-card_price">
                                    <span>@food.Price лв.</span>
                                </div>
                                <div class="food-card_order-count">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <button onclick="minus(event)" id="minus"class="btn btn-outline-secondary minus-btn" type="button">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-lg" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M2 8a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11A.5.5 0 0 1 2 8Z" />
                                                </svg>
                                            </button>
                                        </div>
                                            <input asp-for="@Model.Where(x=>x.Id==food.Id).FirstOrDefault()!.count" id="input" value="0" type="text" class="form-control">
                                        <div class="input-group-append">
                                            <button onclick="plus(event)" id="plus"  class="btn btn-outline-secondary add-btn" type="button" >
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z" />
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <div class="text-center">
                               
                                    <button  type="submit">Subscribe</button>
                               
                        </div>
                    </div>
                </div>
                
            </div>
            </form>
        }
        
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>


 @* <!-- Source -->
    <div class="card flex-row">
        <img class="card-img-left example-card-img-responsive" src="https://images.immediate.co.uk/production/volatile/sites/30/2017/06/healthy-nicoise-09b6cd9.jpg" style="width:200px;height:200px" />
  <div class="card-body">
    <h4 class="card-title h5 h4-sm">Овчарска салата</h4>
    <p>Продукти: домати,краставици, зелен лук,печени чушки,стерелизирани гъби,шунка,сирене,яйца сварени,магданоз, маслини</p>
    <p>Грамаж: 250гр.</p>
    <p>Време за приготвяне: 30мин</p>
    <p>Калории: 250ckal</p>
    <p>Цена: 8.80лв.</p>
  </div>
</div>*@
   </div>
    <!-- Source -->
   @* <div class="card row">
        <img class="card-img-left example-card-img-responsive" src="https://images.immediate.co.uk/production/volatile/sites/30/2017/06/healthy-nicoise-09b6cd9.jpg" style="width:200px;height:200px" />
        <div class="col-10">
            <div class="card-body">
                <h4 class="card-title h5 h4-sm">Left image</h4>
                <p class="card-text">Example text</p>
            </div>
        </div>
        <div class="col-2">
            <p>цана</p>
            <p>количество</p>
            <p>купи</p>
        </div>
    </div>
    </div>*@
 

OnlineRestaurantMenu/Views/Menu/DrinksTypes.cshtml
@using OnlineRestaurantMenu.Models.Menu;
@model IEnumerable<MenuFoodModel>
@{
    
}
    <div class="container pb-5" style="background-color:rgb(220,220,220,0.1)">
    <partial name="_MenuPartial" />
        <div class="row justify-content-center">
        @foreach (var type in Model)
        {

            <div class="ar-image m-3">
            <div style="background: url('@type.Image');  background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            border-radius:30px" class="article-image"></div>
            <p class="h2"> @Html.ActionLink(type.Type, "DrinksByType", new { Id = type.Id })</p>
            </div>
        }
        </div>
    </div>
<link rel="stylesheet" href="~/css/CardTypes.css" asp-append-version="true" />

OnlineRestaurantMenu/Views/Menu/FoodsByType.cshtml
@using OnlineRestaurantMenu.Models.Product;
@model IEnumerable<ProductModel>


@{
   
}

<div class="container pb-5" style="background-color:rgb(220,220,220,0.1)">

        <div class="p-5  bg-image" style="
        background-image: url('https://i.postimg.cc/9XLYf0xf/pexels-ella-olsson-1640777.jpg');
        background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
border-end-end-radius: 80px;
border-end-start-radius:80px;
  position: relative;
        height: 380px;"></div>

    <div class="text-center mb-2">
        <h1 class="text-black">Меню</h1>

        <div class="d-flex justify-content-center">
            <a class="nav-link btn btn-primary" style="color:white; margin-right:10px" asp-controller="Menu" asp-action="FoodsTypes">Храни</a>
            <a class="nav-link btn btn-primary" style="color:white" asp-controller="Menu" asp-action="DrinksTypes">Напитки</a>
        </div>

    </div>
    <div class="input-group px-5">
        <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
        <button type="button" class="btn btn-primary">search</button>
    </div>
    <div class="row px-5 mt-3">
        @foreach (var food in Model)
        {
            <form asp-action="AddInOrder" asp-controller="Product" method="post" enctype="multipart/form-data">
            <div class="col-sm-6 col-md-6 col-lg-4">
                <div class="food-card">
                    <div class="food-card_img">
                            <input type="hidden" asp-for="@Model.Where(x=>x.Id==food.Id).FirstOrDefault().Id" />
                        <img src="@food.Image" alt="">
                    </div>
                    <div class="food-card_content">
                        <div class="food-card_title-section">
                            <a href="#!" class="food-card_title">@food.Name</a>
                            <div class="row">
                                <div class="col text-center">

                                    <img src="~/svg/weight-svgrepo-com.svg" alt="" width="25px" height="25px" style="vertical-align: text-bottom;" />@food.Size


                                </div>
                                <div class="col text-center">
                                    <img src="~/svg/stopwatch.svg" alt="" width="25px" height="25px" style="vertical-align: text-bottom;" />@food.TimeToGet мин.
                                </div>
                                <div class="col text-center">
                                    <img src="~/svg/egg-fried.svg" alt="" width="25px" height="25px" style="vertical-align: text-bottom;" />@food.Calories Kcal
                                </div>

                            </div>
                            <p>@food.Description</p>
                        </div>
                        <div class="food-card_bottom-section">
                            @*<div class="space-between">
                        <div>
                        <span class="fa fa-fire"></span> 220 - 280 Kcal
                        </div>
                        </div>*@
                            <hr>
                            <div class="space-between">
                                <div class="food-card_price">
                                    <span>@food.Price лв.</span>
                                </div>
                                <div class="food-card_order-count">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <button onclick="minus(event)" id="minus"class="btn btn-outline-secondary minus-btn" type="button">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-lg" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M2 8a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11A.5.5 0 0 1 2 8Z" />
                                                </svg>
                                            </button>
                                        </div>
                                            <input id="input" value="0" type="text" class="form-control">
                                        <div class="input-group-append">
                                            <button onclick="plus(event)" id="plus"  class="btn btn-outline-secondary add-btn" type="button" >
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z" />
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <div class="text-center">
                               
                                    <button  type="submit">Subscribe</button>
                               
                        </div>
                    </div>
                </div>
                
            </div>
            </form>
        }
        
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>


 @* <!-- Source -->
    <div class="card flex-row">
        <img class="card-img-left example-card-img-responsive" src="https://images.immediate.co.uk/production/volatile/sites/30/2017/06/healthy-nicoise-09b6cd9.jpg" style="width:200px;height:200px" />
  <div class="card-body">
    <h4 class="card-title h5 h4-sm">Овчарска салата</h4>
    <p>Продукти: домати,краставици, зелен лук,печени чушки,стерелизирани гъби,шунка,сирене,яйца сварени,магданоз, маслини</p>
    <p>Грамаж: 250гр.</p>
    <p>Време за приготвяне: 30мин</p>
    <p>Калории: 250ckal</p>
    <p>Цена: 8.80лв.</p>
  </div>
</div>*@
   </div>
    <!-- Source -->
   @* <div class="card row">
        <img class="card-img-left example-card-img-responsive" src="https://images.immediate.co.uk/production/volatile/sites/30/2017/06/healthy-nicoise-09b6cd9.jpg" style="width:200px;height:200px" />
        <div class="col-10">
            <div class="card-body">
                <h4 class="card-title h5 h4-sm">Left image</h4>
                <p class="card-text">Example text</p>
            </div>
        </div>
        <div class="col-2">
            <p>цана</p>
            <p>количество</p>
            <p>купи</p>
        </div>
    </div>
    </div>*@
 

OnlineRestaurantMenu/Views/Menu/FoodsTypes.cshtml
@using OnlineRestaurantMenu.Models.Menu;
@model IEnumerable<MenuFoodModel>
    @{
      
    }
    <div class="container pb-5" style="background-color:rgb(220,220,220,0.1)">
    <partial name="_MenuPartial" />
        <div class="row justify-content-center">
            @foreach (var type in Model)
            {
                    
                <div class="ar-image m-3">
                <div style="background: url('@type.Image');  background-position: center;
                background-repeat: no-repeat;
                background-size: cover;
                border-radius:30px" class="article-image">
                </div>
                <p class="h2"> @Html.ActionLink(type.Type, "FoodsByType", new { Id = type.Id })</p>
                </div>
            }
        </div>
    </div>
<link rel="stylesheet" href="~/css/CardTypes.css" asp-append-version="true" />

OnlineRestaurantMenu/Views/Menu/_MenuPartial.cshtml
<div>
   <div class="p-5  bg-image" style="
      background-image: url('https://i.postimg.cc/9XLYf0xf/pexels-ella-olsson-1640777.jpg');
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      border-end-end-radius: 80px;
      border-end-start-radius:80px;
      position: relative;
      height: 380px;"></div>
   <div class="text-center mb-2">
      <h1 class="text-black">Меню</h1>

        <div class="d-flex justify-content-center">
            <a class="nav-link btn btn-primary" style="color:white; margin-right:10px" asp-controller="Menu" asp-action="FoodsTypes">Храни</a>
            <a class="nav-link btn btn-primary" style="color:white" asp-controller="Menu" asp-action="DrinksTypes">Напитки</a>
        </div>
     
   </div>
  
</div>